name: Custom Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  tests:
    name: Custom Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install SUDO Package
        run: |
          apt update && apt install sudo
      - name: Checkout ISPC-Kit Repo
        uses: actions/checkout@v2
      -name: Execute Custom Tests
        run: |
          cd test
          sudo ./test.sh
